name: "CI"

env:
  DOTENV_CONFIG_PATH: "./.env.example"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "16.x"

      - name: "Install the dependencies"
        run: "yarn install --immutable"
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "yarn typechain"
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}

      # skip lint for now to see if tests pass
      # - name: "Lint the code"
      #   run: "yarn lint"
      #   env:
      #     INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      #     MNEMONIC: ${{ secrets.MNEMONIC }}

      # - name: "Add lint summary"
      #   run: |
      #     echo "## Lint results" >> $GITHUB_STEP_SUMMARY
      #     echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Test the contracts and generate the coverage report"
        run: "yarn coverage"
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}

      - name: "Test the use cases"
        run: "yarn test:usecase"
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
